"""init schema

Revision ID: 077a7e8c10ae
Revises: 
Create Date: 2026-05-15 14:57:06.578206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '077a7e8c10ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('datadis_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('dni_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encryption_key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('active', 'invalid', 'expired', name='credentialstatus'), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datadis_credentials_user_id'), 'datadis_credentials', ['user_id'], unique=True)
    op.create_table('datadis_sync_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='syncstatus'), nullable=False),
    sa.Column('type', sa.Enum('supplies', 'contracts', 'consumption', name='synctype'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datadis_sync_jobs_user_id'), 'datadis_sync_jobs', ['user_id'], unique=False)
    op.create_table('homes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homes_user_id'), 'homes', ['user_id'], unique=False)
    op.create_table('supply_points',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('home_id', sa.Uuid(), nullable=False),
    sa.Column('cups', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('distributor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supply_points_cups'), 'supply_points', ['cups'], unique=True)
    op.create_index(op.f('ix_supply_points_home_id'), 'supply_points', ['home_id'], unique=False)
    op.create_table('consumption_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supply_point_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('consumption_kwh', sa.Float(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('datadis', 'manual', name='consumptionsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supply_point_id'], ['supply_points.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supply_point_id', 'timestamp', name='uq_consumption_supply_timestamp')
    )
    op.create_index(op.f('ix_consumption_records_supply_point_id'), 'consumption_records', ['supply_point_id'], unique=False)
    op.create_index(op.f('ix_consumption_records_timestamp'), 'consumption_records', ['timestamp'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supply_point_id', sa.Uuid(), nullable=False),
    sa.Column('contract_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('tariff_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('power_kw', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='contractstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supply_point_id'], ['supply_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_supply_point_id'), 'contracts', ['supply_point_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_supply_point_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_consumption_records_timestamp'), table_name='consumption_records')
    op.drop_index(op.f('ix_consumption_records_supply_point_id'), table_name='consumption_records')
    op.drop_table('consumption_records')
    op.drop_index(op.f('ix_supply_points_home_id'), table_name='supply_points')
    op.drop_index(op.f('ix_supply_points_cups'), table_name='supply_points')
    op.drop_table('supply_points')
    op.drop_index(op.f('ix_homes_user_id'), table_name='homes')
    op.drop_table('homes')
    op.drop_index(op.f('ix_datadis_sync_jobs_user_id'), table_name='datadis_sync_jobs')
    op.drop_table('datadis_sync_jobs')
    op.drop_index(op.f('ix_datadis_credentials_user_id'), table_name='datadis_credentials')
    op.drop_table('datadis_credentials')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
