"""add saved_reports table

Revision ID: 11a39e9e65b0
Revises: f363c333ee8f
Create Date: 2026-05-27 19:42:20.444903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '11a39e9e65b0'
down_revision: Union[str, Sequence[str], None] = 'f363c333ee8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supply_point_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('period_from', sa.DateTime(), nullable=False),
    sa.Column('period_to', sa.DateTime(), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('total_kwh', sa.Float(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('report_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_reports_supply_point_id'), 'saved_reports', ['supply_point_id'], unique=False)
    op.create_index(op.f('ix_saved_reports_user_id'), 'saved_reports', ['user_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_saved_reports_user_id'), table_name='saved_reports')
    op.drop_index(op.f('ix_saved_reports_supply_point_id'), table_name='saved_reports')
    op.drop_table('saved_reports')
