"""add forecast_records table

Revision ID: 4d8e0c3c698b
Revises: cbfbc0c45b99
Create Date: 2026-05-26 18:51:55.303928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d8e0c3c698b'
down_revision: Union[str, Sequence[str], None] = 'cbfbc0c45b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('home_id', sa.Uuid(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_kwh', sa.Float(), nullable=False),
    sa.Column('lower_kwh', sa.Float(), nullable=False),
    sa.Column('upper_kwh', sa.Float(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('home_id', 'forecast_date', name='uq_forecast_home_date')
    )
    op.create_index(op.f('ix_forecast_records_forecast_date'), 'forecast_records', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_forecast_records_home_id'), 'forecast_records', ['home_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_records_home_id'), table_name='forecast_records')
    op.drop_index(op.f('ix_forecast_records_forecast_date'), table_name='forecast_records')
    op.drop_table('forecast_records')
    # ### end Alembic commands ###
