"""add_recommendation_feedback_table

Revision ID: 6dba1e4d4530
Revises: a89c76e7b41b
Create Date: 2026-06-03 18:19:22.214286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6dba1e4d4530'
down_revision: Union[str, Sequence[str], None] = 'a89c76e7b41b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('home_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recommendation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_feedback_home_id'), 'recommendation_feedback', ['home_id'], unique=False)
    op.create_index(op.f('ix_recommendation_feedback_recommendation_id'), 'recommendation_feedback', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_feedback_recommendation_id'), table_name='recommendation_feedback')
    op.drop_index(op.f('ix_recommendation_feedback_home_id'), table_name='recommendation_feedback')
    op.drop_table('recommendation_feedback')
    # ### end Alembic commands ###
