"""add tariff rates to contracts

Revision ID: 83a4776f3243
Revises: 4d8e0c3c698b
Create Date: 2026-05-26 19:10:40.423947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '83a4776f3243'
down_revision: Union[str, Sequence[str], None] = '4d8e0c3c698b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('energy_rate_kwh', sa.Float(), nullable=True))
    op.add_column('contracts', sa.Column('power_rate_peak_kw_day', sa.Float(), nullable=True))
    op.add_column('contracts', sa.Column('power_rate_valley_kw_day', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'power_rate_valley_kw_day')
    op.drop_column('contracts', 'power_rate_peak_kw_day')
    op.drop_column('contracts', 'energy_rate_kwh')
    # ### end Alembic commands ###
