"""extend_contract_tariff_fields

Revision ID: a529a0f1a69d
Revises: 11a39e9e65b0
Create Date: 2026-05-28 19:10:46.127688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a529a0f1a69d'
down_revision: Union[str, Sequence[str], None] = '11a39e9e65b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('energy_rate_p1_kwh', sa.Float(), nullable=True))
    op.add_column('contracts', sa.Column('energy_rate_p2_kwh', sa.Float(), nullable=True))
    op.add_column('contracts', sa.Column('iee_pct', sa.Float(), nullable=False, server_default='5.11269'))
    op.add_column('contracts', sa.Column('iva_pct', sa.Float(), nullable=False, server_default='10.0'))
    op.add_column('contracts', sa.Column('meter_rent_eur_month', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('contracts', sa.Column('cargos_pct', sa.Float(), nullable=False, server_default='0.0'))
    op.create_foreign_key(None, 'homes', 'weather_locations', ['weather_location_id'], ['id'])
    op.alter_column('weather_records', 'location_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    op.create_foreign_key(None, 'weather_records', 'weather_locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weather_records', type_='foreignkey')
    op.alter_column('weather_records', 'location_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    op.drop_constraint(None, 'homes', type_='foreignkey')
    op.drop_column('contracts', 'cargos_pct')
    op.drop_column('contracts', 'meter_rent_eur_month')
    op.drop_column('contracts', 'iva_pct')
    op.drop_column('contracts', 'iee_pct')
    op.drop_column('contracts', 'energy_rate_p2_kwh')
    op.drop_column('contracts', 'energy_rate_p1_kwh')
    # ### end Alembic commands ###
