"""add anomaly_records table

Revision ID: ab91551df0f7
Revises: 83a4776f3243
Create Date: 2026-05-26 21:08:30.359459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab91551df0f7'
down_revision: Union[str, Sequence[str], None] = '83a4776f3243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('home_id', sa.Uuid(), nullable=False),
    sa.Column('anomaly_date', sa.Date(), nullable=False),
    sa.Column('actual_kwh', sa.Float(), nullable=False),
    sa.Column('predicted_kwh', sa.Float(), nullable=False),
    sa.Column('residual_kwh', sa.Float(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('home_id', 'anomaly_date', name='uq_anomaly_home_date')
    )
    op.create_index(op.f('ix_anomaly_records_anomaly_date'), 'anomaly_records', ['anomaly_date'], unique=False)
    op.create_index(op.f('ix_anomaly_records_home_id'), 'anomaly_records', ['home_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomaly_records_home_id'), table_name='anomaly_records')
    op.drop_index(op.f('ix_anomaly_records_anomaly_date'), table_name='anomaly_records')
    op.drop_table('anomaly_records')
    # ### end Alembic commands ###
