"""add lower_upper_kwh to anomaly_records

Revision ID: b513f0a91c59
Revises: ab91551df0f7
Create Date: 2026-05-26 21:26:35.328024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b513f0a91c59'
down_revision: Union[str, Sequence[str], None] = 'ab91551df0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomaly_records', sa.Column('lower_kwh', sa.Float(), nullable=False, server_default='0'))
    op.add_column('anomaly_records', sa.Column('upper_kwh', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anomaly_records', 'upper_kwh')
    op.drop_column('anomaly_records', 'lower_kwh')
    # ### end Alembic commands ###
