"""add usage_profiles table

Revision ID: cbfbc0c45b99
Revises: b2c3d4e5f6a7
Create Date: 2026-05-25 20:48:03.459507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cbfbc0c45b99'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('home_id', sa.Uuid(), nullable=False),
    sa.Column('occupants', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('home_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('heating_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hot_water', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('appliances', sa.JSON(), nullable=True),
    sa.Column('home_days', sa.JSON(), nullable=True),
    sa.Column('work_from_home', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wake_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sleep_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('laundry_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cooking_meals', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_profiles_home_id'), 'usage_profiles', ['home_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_profiles_home_id'), table_name='usage_profiles')
    op.drop_table('usage_profiles')
    # ### end Alembic commands ###
